name: klontong_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  retrofit: ^4.4.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  injectable: ^2.4.4
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  flutter_easyloading: ^3.0.5
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  package_info_plus: ^8.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  fluttertoast: ^8.2.8
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  animated_bottom_navigation_bar: ^1.3.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  top_snackbar_flutter: ^3.1.0
  draggable_home: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
